### ISSUE TITLE
Random whitespace

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/vtebench#4]
When just running a simple bench like this `ctx.write_all(b"y")` in a loop, I do not get a constant feed of `y` without any interruptions, but every once in a while there's just a whitespace ` `.

The output looks a bit like this:
`yy yyyyyy y yyyyyy y y yyyyy yyy yyyy`

I was not able to see any pattern in this and flushing did not change this. It happens when doing `cat output` and when just running it directly (which should lead to the same output anyways as far as I can tell).

**Comment by jwilm** [comment]
You’ll want to write y\n. Not sure why you’re seeing that, though.

**Comment by chrisduerr** [comment]
Yeah I know I'd want to write `y\n`, but that has the same issue that sometimes it just writes empty lines. I was just trying to break it down to the basics. Even using `ctx.write_ascii(_)` will cause this issue for me.

I've also tried just `write` and played with running `flush` after every write. Nothing fixed it.

**Comment by jwilm** [comment]
Can you share the whole code?

**Comment by jwilm** [comment]
Wasn't able to reproduce; have a working impl on master.

**Comment by chrisduerr** [comment]
Yeah totally my bad. Apparently this happens when you run `ctx.setaf(0)`.

This of course sets the foreground color of the character to the background color of the terminal (at least for my cterm colors). So I was just being stupid. :D
