### ISSUE TITLE
Scrolling in alternate screen buffer

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/vtebench#5]
I was just testing the `scrolling` implementations and saw that these use the alternate screen buffer. So I was curious why this is done. I understand that the alternate screen buffer might do stuff differently, but shouldn't the very basic `scrolling` test just use the default screen buffer?

They also use the `YES` constant which already is filled with quite a few lines. This probably makes things quicker, but that doesn't really seem to be the goal here. If they would just print a single `y`, it would be possible to also allow the `-c` color flag to change the color with every line, which I think would make some sense with this test.

This diff shows the approach I had in mind:
<details>

```diff
diff --git a/src/bench.rs b/src/bench.rs
index c103990..43f1235 100644
--- a/src/bench.rs
+++ b/src/bench.rs
@@ -82,14 +82,15 @@ pub fn scrolling_in_region<W: Write>(ctx: &mut Context<W>, options: &Options) ->
 
 pub fn scrolling<W: Write>(ctx: &mut Context<W>, options: &Options) -> Result<usize> {
     let mut written = 0;
+    let mut rng = rand::thread_rng();
 
-    written += ctx.smcup()?;
     while written < options.bytes {
-        ctx.write_all(YES)?;
-        written += YES.len();
+        if options.colorize {
+            written += ctx.setaf(rng.gen_range(0, 8))?;
+        }
+        ctx.write_all(b"y\n")?;
+        written += b"y\n".len();
     }
-    ctx.rmcup()?;
-    ctx.sgr0()?;
 
     Ok(written)
 }
```

</details>

**Comment by jwilm** [comment]
You're totally right about the alt screen changes being necessary, I wasn't thinking about it properly last night. I was just annoyed that it was blasting all the old output in the main view 🙃 .

Regarding colorize here, it's starting to test multiple things. Right now it's just testing line feed with single character outputs. This is two bytes per line. If we start adding color, that's another 5 bytes per line and hitting additional code paths in the emulator to change color state.

**Comment by chrisduerr** [comment]
Yeah it would definitely test a path that doesn't really have anythingh to do with the basic scrolling test. But I thought it would be fairly simple to support the flag with this test and might show some performance differences.
