### ISSUE TITLE
Make use of #[bench] feature

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/vtebench#7]
So initially when testing the scrollback PR of alacritty, I've written a small toolkit to help me check for possible performance regressions, you can take a look at this tool here:
https://github.com/chrisduerr/terminal-benchmarks

I really like the idea of this tool to just write to a file which has the necessary escape sequences to simulate the output without any overhead of creating that output, but I think having to run `time` for every test is a bit tedious, especially because you might want to run it a couple of times to check for deviations.

A possible solution for this might be making use of the `#[bench]` feature in rust, it could just be a simple `println!("{}", file_content);` and then that could be benchmarked.
The biggest problem with this is probably that I haven't been able to figure out how to control the number of iterations, but I think it might be an interesting idea to at least explore this a bit.

**Comment by jwilm** [comment]
As it turns out, the `#[bench]` feature is not very good for macro benchmarks like we are doing here. There are certain assumptions built into it such as very short run-time for code under test, and the tool pretty much breaks when that's violated. Great idea though!

**Comment by chrisduerr** [comment]
Hmm yeah that's very unfortunate. I guess a simple bash script might help with running tests multiple times and taking an average.

**Comment by jwilm** [comment]
Yeah I was thinking a bash script would be the way to go. My penultimate goal with vtebench is to have automated performance testing with a headless renderer on travis. Potentially we can use/create some third party service to track benchmark performance over time.

**Comment by chrisduerr** [comment]
Yeah that was something I was curious about. It seems like a good idea to just have an automated suite to run all these tests, then maybe graph it online so a regression would be clearly visible.
